Fixed problems where mysql cache not cleared.

diff --git a/ejbca_restore b/ejbca_restore
--- a/ejbca_restore
+++ b/ejbca_restore
@@ -15,6 +15,10 @@
 # to e.g. an NFS share
 BACKUP_DIR='/var/opt/backups'
 
+# The service name of the appserver
+#APPSRV_TYPE=jboss
+APPSRV_TYPE=wildfly
+
 # The passphrase which protects the backup, clear this variable
 # to make the script ask for the passphrase.
 PWD=
@@ -32,23 +36,25 @@ if [ "$(id -u)" != "0" ]; then
   exit 1
 fi
 
-# MariaDB must be stopped before the backup is restored
+# The database should be stopped before the restore process starts.
+# Technically it is possible to do the restore with the database running
+# but it could result in weird errors when incoming requests are processed.
 if systemctl is-active --quiet mysql; then
   read -p 'Cannot restore a backup while MariaDB is running. Do you want to stop MariaDB now? (y/N) ' stopdb
   if [ "$stopdb" != "y" ] && [ "$stopdb" != "Y" ]; then
     exit 1
   else
-    systemctl stop mysql
+    read -s -p 'Enter the MariaDB root password: ' root_pwd 
+    mysqladmin -uroot -p"$root_pwd" -h127.0.0.1 --protocol=tcp shutdown
+    if [ $? -ne 0 ]; then
+      echo "Shutdown of MariaDB failed with non-zero exit code."
+      exit 1
+    fi
   fi
 fi
 
-# Check if MariaDB is running again, just to make sure
-if systemctl is-active --quiet mysql; then
-  echo '** ERROR ** MariaDB is still running, stop MariaDB manually and run this script again.'
-  exit 1
-fi
-
 # Warn the user about potential loss of data
+echo ""
 read -p '** WARNING ** You are about to wipe the existing database! Do you want to proceed? (y/N) ' wipe
 if [ "$wipe" != "y" ] && [ "$wipe" != "Y" ]; then
   echo 'Aborting restore.'
@@ -111,14 +117,18 @@ xtrabackup --prepare --target-dir=/var/lib/mysql/
 
 chown -R mysql:mysql /var/lib/mysql
 
-options=("Create a new cluster - Use this option if you are restoring the database of the first node in a cluster." "Start MariaDB normally - Use this option if you are restoring a standalone instance of EJBCA or if you want to join a newly restored node to an existing cluster." "Do nothing - Choose this option if you want to manually start MariaDB later.")
+options=("Create a new cluster - Use this option if you are restoring the database of the first node in a cluster." "Start MariaDB normally - Use this option if you are restoring a standalone instance of EJBCA." "Do nothing - Choose this option if you want to manually start MariaDB later.")
 echo 'The database files are restored, but MariaDB is not running yet. What should I do next? '
 PS3='Choose an option '
 select opt in "${options[@]}"; do
   case "$REPLY" in
-  1 ) galera_new_cluster
+  1 ) mysqld &
+      galera_new_cluster
+      sudo systemctl restart "$APPSRV_TYPE"
       break;;
-  2 ) systemctl start mysql
+  2 ) mysqld &
+      sudo systemctl start mysql
+      sudo systemctl restart "$APPSRV_TYPE"
       break;;
   3 ) break;;
   * ) echo "Invalid option $REPLY. Try again..."
